version: vTest1
dir_input: InitData_Test1
list_ROIs_all: vTest1/lists/MUSE/list_MUSE_all.csv
list_ROIs_single: vTest1/lists/MUSE/list_MUSE_single.csv
list_ROIs_primary: vTest1/lists/MUSE/list_MUSE_primary.csv
list_derived_ROIs: vTest1/lists/MUSE/list_MUSE_mapping_derived.csv
corr_type: normICV
model_combat: vISTAG1/COMBAT/combined_DLMUSE_raw_COMBATModel.pkl.gz
model_SPARE-AD: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-AD_Model.pkl.gz
model_SPARE-Age: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-Age_Model.pkl.gz
model_SPARE-Diabetes: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-Diabetes_Model.pkl.gz
model_SPARE-Hyperlipidemia: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-Hyperlipidemia_Model.pkl.gz
model_SPARE-Hypertension: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-Hypertension_Model.pkl.gz
model_SPARE-Obesity: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-Obesity_Model.pkl.gz
model_SPARE-Smoking: vISTAG1/SPARE/combined_DLMUSE_raw_COMBAT_SPARE-Smoking_Model.pkl.gz
SPARE_types:
 - AD
 - Age
 - Diabetes
 - Hyperlipidemia
 - Hypertension
 - Obesity
 - Smoking 
roi_types:
 - DLMUSE
 
