version: vTest1
dir_input: InitData_Test1
dir_output: NiChart_vTest1
list_ROIs_all: list_MUSE_all.csv
list_ROIs_selected: list_MUSE_primary_single.csv
model_combat: COMBAT/COMBAT_vtest1/combined_MUSE_raw_COMBATModel.pkl.gz
list_SPARE_models: list_SPARE_models.csv
SPARE_types:
 - AD
roi_types:
 - MUSE
corr_types:
 - raw
